### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by liantianji** [xingrz/Knob-FW#1]
enc_state =ENC_TABLE[enc_state & 0xf][pin_state];改成enc_state = E3NC_TABLE[enc_state & 0xf][pin_state]

**Comment by xingrz** [comment]
> E3NC_TABLE

你认真的？

https://github.com/xingrz/Knob-FW/blob/ad30fa5a8d28cc8432f39487b78d51d79f88d894/main/src/task_rotary.c#L29

**Comment by liantianji** [comment]
我重新拉一次仓库看看，先前有定义 E3NC_TABLE的

**Comment by xingrz** [comment]
> 先前有定义 E3NC_TABLE的

你自己手滑吧…看提交记录就知道从来没出现过 E3NC
